encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("new_page", views.new_page, name="new_page"),
    path("edit_page/<str:entry_name>", views.edit_page, name="edit_page"),
    path("random", views.random, name="random"),
    path("<str:entry_name>", views.entry, name="entry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
###################################################################
# views.py
#
# Programmeerplatform
# Joris Oud
#
# - Implements the views for the encyclopedia application
###################################################################


from django import forms
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from markdown2 import markdown
from random import choice

from . import util

def validate_title(title):
    """Validation function for the Django form 'New_page_form'. Raises a
      ValidationError when a newly created page name already exists."""

    for entry in util.list_entries():
        if title.lower() == entry.lower():
            raise ValidationError(f"A page with the name {title} already exists.")

class New_page_form(forms.Form):
    """Creates a Django form to create a new wiki page. Attrubutes:
      - title(string): The title of the page.
      - page_contentes(string): The contents of the page in markdown format."""

    title = forms.CharField(label="Page Title", validators=[validate_title])
    page_contents = forms.CharField(label="page Contents", widget=forms.Textarea)

class Edit_page_form(forms.Form):
    """Creates a Django form to edit a wiki page. Attrubute:
      - page_contentes(string): The contents of the page in markdown format."""

    page_contents = forms.CharField(label="page Contents", widget=forms.Textarea)

def index(request):
    """Renders the home page of the encyclopedia app."""

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, entry_name):
    """Renders the requested entry page. If requested entry page does not exist,
      renders an error page. Needs an entry name (string) as second argument."""

    if entry_name not in util.list_entries():
        return render(request, "encyclopedia/entry_error.html")

    return render(request, "encyclopedia/entry.html",{
        "entry_name": entry_name,
        "entry_text": markdown(util.get_entry(entry_name))
    })

def search(request):
    """Renders an entry page if the search query matches the entry name exactly,
      or else renders a page with a list of entries of which the query is a substring. 
      The search is case insensitive."""

    query = request.GET.get("q", "")
    results_list = []

    for ent in util.list_entries():
        if query.lower() == ent.lower():
            return entry(request, ent)
        elif query.lower() in ent.lower():
            results_list.append(ent)

    return render(request, "encyclopedia/results.html",{
        "query": query,
        "results_list": results_list
    })

def new_page(request):
    """When requested with GET, renders a page where the user can create a new page. 
      When requested with POST, saves the page and redirects to the created page. If 
      the posted page was not valid, returns to the create page with an error message."""

    if request.method != "POST":
        return render(request, "encyclopedia/new_page.html", {
            "form": New_page_form()
        })

    form = New_page_form(request.POST)
    if form.is_valid():
        title = form.cleaned_data["title"]
        page_contents = form.cleaned_data["page_contents"]
        util.save_entry(title, page_contents)

        return HttpResponseRedirect(reverse("encyclopedia:entry", args=[title]))
    else:
        return render(request, "encyclopedia/new_page.html", {
            "form": form
        })

def edit_page(request, entry_name):
    """Accepts an entry name (string) as second argument. When requested with GET, 
      renders a page where the user can edit that page. When requested with POST, saves 
      the changes and redirects to the edited page. If the posted page was not valid, 
      returns to the edit page with an error message."""

    if request.method != "POST":
        return render(request, "encyclopedia/edit_page.html", {
            "entry_name": entry_name,
            "form": Edit_page_form(initial={"page_contents": util.get_entry(entry_name)})
        })

    form = Edit_page_form(request.POST)
    if form.is_valid():
        util.save_entry(entry_name, form.cleaned_data["page_contents"])
        return HttpResponseRedirect(reverse("encyclopedia:entry", args=[entry_name]))
    else:
        return render(request, "encyclopedia/new_page.html", {
            "form": form
        })

def random(request):
    """Calls the entry function with a random entry name."""

    return entry(request, choice(util.list_entries()))

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit {{ entry_name }}
{% endblock %}

{% block body %}
    <h1>Edit {{ entry_name }}</h1>

    <form action="{% url 'encyclopedia:edit_page' entry_name %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Save Page">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry_name }}
{% endblock %}

{% block body %}
    {{ entry_text|safe }}
{% endblock %}

{% block nav %}
    <a href="{% url 'encyclopedia:edit_page' entry_name %}">Edit Page</a>
{% endblock %}

encyclopedia/templates/encyclopedia/entry_error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    error: page not found
{% endblock %}

{% block body %}
<h1>Error</h1>
<p>requested page not found</p>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% empty %}
            <li>There are no pages yet. Click 'Create New Page' to make a page.</li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h1>Create new page</h1>

    <form action="encyclopedia:new_page" method="POST">
        {% csrf_token %}
        <input type="text" name="title" placeholder="Enter page title" autofocus>
        <br>
        Write the contents of your new page as markdown text in the area below.
        <textarea name="new_page_text"></textarea>
        <br>
        <input type="submit" value="Save Page">
    </form>




{% endblock %}

encyclopedia/templates/encyclopedia/results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search results
{% endblock %}

{% block body %}
    <h1>Search results for {{ query }}</h1>

    <ul>
        {% for result in results_list %}
            <li><a href="{% url 'encyclopedia:entry' result %}">{{ result }}</a></li>
        {% empty %}
            No matches found.
        {% endfor %}
    </ul>

{% endblock %}